### ISSUE TITLE
Asking for password when compiling 

### ISSUE THREAD

**Issue by Hedmun395** [vpenades/MonoGame.AnimAndPBR#4]
I'm trying to compile the project, but a password is being asked  What I do is:

* I git clone the project
* Open the project with VS2019 (latest)
* Build -> Rebuild solution

A popup opens, asking a login and password to connect to nuget.pkg.github.com
Entering the menu Tools > Nuget package manager > Manage nuget packages asks for the 

any ideas?
thanks!

**Comment by vpenades** [comment]
Ah, I uploaded a temporary nuget.config by mistake, I've just removed it.

Update the repo and try again.
